spring.application.name=forohub

# Configuración de la base de datos (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/forohub_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuración de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Configuración de Seguridad y JWT
api.security.secret=${JWT_SECRET}

# Corrección para la propiedad Deprecated
spring.web.error.include-stacktrace=never

logging.level.org.springframework.security=DEBUG